"""Qualitative tests generated by vaibify."""
# vaibify-template-hash: 58c5e9fcc16b62ec

import json
import os
import pathlib

import pytest


def _fdictLoadQualitativeStandards():
    """Load the qualitative standards JSON file."""
    sJsonPath = str(
        pathlib.Path(__file__).parent / "qualitative_standards.json"
    )
    with open(sJsonPath, encoding="utf-8") as fileHandle:
        return json.load(fileHandle)


_DICT_STANDARDS = _fdictLoadQualitativeStandards()
_LIST_STANDARDS = _DICT_STANDARDS["listStandards"]
_STEP_DIRECTORY = str(pathlib.Path(__file__).parent.parent)


def _flistLoadColumns(sFullPath, sFormat):
    """Load column names from a tabular or array file."""
    if sFormat == "npz":
        import numpy as np
        return list(np.load(sFullPath, allow_pickle=False).files)
    if sFormat in ("npy", "hdf5"):
        return []
    if sFormat == "csv":
        import csv
        with open(sFullPath, newline="", encoding="utf-8") as fileHandle:
            reader = csv.DictReader(fileHandle)
            return list(reader.fieldnames or [])
    with open(sFullPath, encoding="utf-8") as fileHandle:
        return fileHandle.readline().split()


def _flistLoadJsonKeys(sFullPath):
    """Load top-level keys from a JSON file."""
    with open(sFullPath, encoding="utf-8") as fileHandle:
        dictData = json.load(fileHandle)
    if isinstance(dictData, dict):
        return list(dictData.keys())
    return []


def _fnCheckExpectedColumns(sFullPath, sFormat, listExpected):
    """Assert all expected columns are present in the file."""
    if not listExpected:
        return
    listActual = _flistLoadColumns(sFullPath, sFormat)
    for sColumn in listExpected:
        assert sColumn in listActual, (
            f"{sFullPath}: missing column {sColumn!r}"
        )


def _fnCheckExpectedJsonKeys(sFullPath, listExpected):
    """Assert all expected JSON keys are present in the file."""
    if not listExpected:
        return
    listActual = _flistLoadJsonKeys(sFullPath)
    for sKey in listExpected:
        assert sKey in listActual, (
            f"{sFullPath}: missing JSON key {sKey!r}"
        )


if not _LIST_STANDARDS:
    def test_no_qualitative_outputs():
        """Placeholder when no qualitative checks are needed."""
        assert True
else:
    @pytest.mark.parametrize(
        "dictStandard",
        _LIST_STANDARDS,
        ids=[s["sFileName"] for s in _LIST_STANDARDS],
    )
    def test_qualitative_check(dictStandard):
        """Validate qualitative properties of a data file."""
        sFullPath = os.path.join(
            _STEP_DIRECTORY, dictStandard["sFileName"],
        )
        sFormat = dictStandard.get("sFormat", "")
        _fnCheckExpectedColumns(
            sFullPath, sFormat,
            dictStandard.get("listExpectedColumns", []),
        )
        _fnCheckExpectedJsonKeys(
            sFullPath,
            dictStandard.get("listExpectedJsonKeys", []),
        )
