#!/usr/bin/env bash
# Auto-generated by vaibify. Reproduces this workflow on a stock host.
# Requires: docker, jq, sha256sum.
set -euo pipefail

sImageRef=$(jq -r .dictContainer.sImageDigest \
    .vaibify/environment.json)
if [ -z "$sImageRef" ] || [ "$sImageRef" = "null" ]; then
    echo "error: sImageDigest missing from .vaibify/environment.json" >&2
    exit 2
fi

docker pull "$sImageRef"
docker run --rm -i -v "$PWD":/work -w /work "$sImageRef" \
    bash -s <<'VAIBIFY_REPRODUCE_EOF'
set -euo pipefail
pip install --require-hashes -r requirements.lock
# Step: AiPowerOverTime
( cd 'AiPowerOverTime' && \
    python dataAiPowerOverTime.py --data-file ../aiWasteHeatData.json --output aiPowerFits.json && \
    python plotAiPowerOverTime.py --power-fits aiPowerFits.json {sPlotDirectory}/aiPowerOverTime.{sFigureType} 
)
# Step: YearsToThresholdContour
( cd 'YearsToThresholdContour' && \
    python dataYearsToThresholdContour.py --power-fits {step:aipowerovertime.aiPowerFits} --output-grid yearsToThresholdGrid.npz --output-markers contourMarkers.json && \
    python plotYearsToThresholdContour.py --years-grid yearsToThresholdGrid.npz --contour-markers contourMarkers.json {sPlotDirectory}/yearsToThresholdContour.{sFigureType} 
)
sha256sum -c MANIFEST.sha256
VAIBIFY_REPRODUCE_EOF
