#!/usr/bin/env bash
# Auto-generated by vaibify. Reproduces this workflow on a stock host.
# Requires: docker, jq, sha256sum, curl (and zstd for a .zst archive).
set -euo pipefail

sImageRef=$(jq -r .dictContainer.sImageDigest \
    .vaibify/environment.json)
if [ -z "$sImageRef" ] || [ "$sImageRef" = "null" ]; then
    echo "error: sImageDigest missing from .vaibify/environment.json" >&2
    exit 2
fi

# The platform the envelope PINS is requested of the pull and of the
# run, in Docker's own spelling (linux/<arch>): without the request a
# multi-architecture reference silently yields whatever build THIS
# host prefers, and a run of the wrong build reproduces nothing. An
# envelope that recorded no architecture is announced, never defaulted
# to this host's -- the same treatment as an absent epoch below. The
# option rides in an array expanded with the guarded-expansion idiom,
# because an empty array under set -u is an error on bash 3.
sImageArchitecture=$(jq -r '.dictContainer.sArchitecture // ""' \
    .vaibify/environment.json)
case "$sImageArchitecture" in
    ''|null) sImageArchitecture="" ;;
esac
if [ -z "$sImageArchitecture" ]; then
    echo "vaibify: .vaibify/environment.json records no image architecture;" >&2
    echo "  the pull and the run cannot request the pinned platform, so a" >&2
    echo "  multi-architecture reference yields this host's build. Regenerate" >&2
    echo "  the environment envelope on the authoring machine to fix it." >&2
    saPlatformOption=()
else
    case "$sImageArchitecture" in
        linux/*) sPlatform="$sImageArchitecture" ;;
        *)       sPlatform="linux/$sImageArchitecture" ;;
    esac
    saPlatformOption=(--platform "$sPlatform")
fi

# The epoch RECORDED when the manifest was pinned, never one derived
# from HEAD here: the commit that published the manifest moved HEAD,
# so a re-derived epoch would date and salt every figure differently
# from the pinned ones and the closing sha256sum -c could not pass.
sSourceDateEpoch=$(jq -r '.iSourceDateEpoch // ""' \
    .vaibify/environment.json)
case "$sSourceDateEpoch" in
    ''|0|*[!0-9]*) sSourceDateEpoch="" ;;
esac
if [ -z "$sSourceDateEpoch" ]; then
    echo "vaibify: .vaibify/environment.json records no iSourceDateEpoch;" >&2
    echo "  this run's figures and archives will carry its wall-clock" >&2
    echo "  time, so sha256sum -c will report every timestamped" >&2
    echo "  artefact (PDF, EPS, PS, SVG) as differing. Regenerate the" >&2
    echo "  environment envelope on the authoring machine to fix it." >&2
fi

# The Zenodo hosts, and nothing else. Rendered from the Python
# client's own table; a record naming any other service is refused.
fnZenodoBaseUrl() {
    case "$1" in
        sandbox) printf '%s' 'https://sandbox.zenodo.org' ;;
        zenodo) printf '%s' 'https://zenodo.org' ;;
        *) return 1 ;;
    esac
}

# Whether one URL is on a host a deposit fetch may contact. The DOI
# resolver is admitted because a record with no recorded service is
# resolved through it; every hop it names is checked here too.
fnUrlWithinAllowlist() {
    case "$1" in
        https://sandbox.zenodo.org/*|https://zenodo.org/*|https://doi.org/*) return 0 ;;
    esac
    return 1
}

# Fetch one URL into a file, following redirects BY HAND: every hop's
# host is checked before the request for it is sent, never after.
# Prints the URL that finally answered, for a caller resolving a DOI.
# A third argument bounds the body: curl refuses a larger announced
# size up front (and recent versions stop a transfer that grows past
# it), so a broken permitted host cannot fill the disk.
fnFetchWithinAllowlist() {
    local sUrl="$1" sOutput="$2" iMaxBytes="${3:-}" iHop=0
    local sAnswer sCode sNext sHost
    local aCurlLimit=()
    if [ -n "$iMaxBytes" ]; then
        aCurlLimit=(--max-filesize "$iMaxBytes")
    fi
    while :; do
        if ! fnUrlWithinAllowlist "$sUrl"; then
            sHost=${sUrl#*://}
            echo "error: refusing to fetch from ${sHost%%/*}: not a" >&2
            echo "       Zenodo host this script knows." >&2
            return 1
        fi
        sAnswer=$(curl -fsS -o "$sOutput" \
            ${aCurlLimit[@]+"${aCurlLimit[@]}"} \
            -w '%{http_code} %{redirect_url}' "$sUrl") || return 1
        sCode=${sAnswer%% *}
        sNext=${sAnswer#* }
        case "$sCode" in
            3??) ;;
            *) printf '%s\n' "$sUrl"; return 0 ;;
        esac
        iHop=$((iHop + 1))
        if [ -z "$sNext" ] || [ "$iHop" -gt 5 ]; then
            echo "error: the deposit redirected without a target, or" >&2
            echo "       more than 5 times; giving up." >&2
            return 1
        fi
        sUrl=$sNext
    done
}

# The record's landing URL. A record that names its service composes
# it from the table and fetches nothing to learn it; a record written
# before the service was recorded is resolved through doi.org, hop by
# hop through the same host check.
fnResolveRecordUrl() {
    local sService="$1" sDoi="$2" sBase
    if [ -n "$sService" ]; then
        if ! sBase=$(fnZenodoBaseUrl "$sService"); then
            echo "error: the deposit record names a Zenodo service this" >&2
            echo "       script does not know: $sService" >&2
            return 1
        fi
        printf '%s/records/%s\n' "$sBase" "${sDoi##*zenodo.}"
        return 0
    fi
    fnFetchWithinAllowlist "https://doi.org/$sDoi" /dev/null
}

fnLoadImageFromArchive() {
    local sDoi sName sSha sService iBytes sRecordUrl sTarball iOutcome
    sDoi=$(jq -r '.dictContainer.dictImageArchive.sVersionDoi // ""' \
        .vaibify/environment.json)
    sName=$(jq -r '.dictContainer.dictImageArchive.sTarballName // ""' \
        .vaibify/environment.json)
    sSha=$(jq -r '.dictContainer.dictImageArchive.sTarballSha256 // ""' \
        .vaibify/environment.json)
    sService=$(jq -r '.dictContainer.dictImageArchive.sZenodoService // ""' \
        .vaibify/environment.json)
    iBytes=$(jq -r '.dictContainer.dictImageArchive.iTarballBytes // 0' \
        .vaibify/environment.json)
    if [ -z "$sDoi" ] || [ -z "$sName" ] || [ -z "$sSha" ]; then
        echo "error: the registry does not serve $sImageRef and this" >&2
        echo "       project archived no copy of its image." >&2
        return 1
    fi
    # The recorded size bounds the download; without one the fetch
    # could be made to fill the disk, so it is refused, never unbounded.
    case "$iBytes" in
        ''|0|*[!0-9]*)
            echo "error: the envelope records no size for the archived" >&2
            echo "       image, so its download cannot be bounded;" >&2
            echo "       refusing to fetch it." >&2
            return 1 ;;
    esac
    echo "Registry pull failed; fetching the archived image from $sDoi"
    sRecordUrl=$(fnResolveRecordUrl "$sService" "$sDoi") || return 1
    sTarball=$(mktemp -t vaibifyImage.XXXXXXXX)
    # An `if` rather than a bare list: under `set -e` a failing LAST
    # element of an and-list exits the script on the spot, skipping
    # the cleanup and the message below and leaving the tarball.
    if fnFetchWithinAllowlist "$sRecordUrl/files/$sName?download=1" \
            "$sTarball" "$iBytes" >/dev/null \
        && [ "$(( $(wc -c < "$sTarball") ))" -eq "$iBytes" ] \
        && echo "${sSha#sha256:}  $sTarball" | sha256sum -c - >/dev/null \
        && fnLoadCheckedTarball "$sTarball" "$sName"; then
        iOutcome=0
    else
        iOutcome=1
    fi
    rm -f "$sTarball"
    if [ "$iOutcome" -ne 0 ]; then
        echo "error: the archived image could not be fetched, was not" >&2
        echo "       the size the envelope records, did not match the" >&2
        echo "       hash it records, or could not be loaded." >&2
    fi
    return "$iOutcome"
}

fnLoadCheckedTarball() {
    local sLoaded
    case "$2" in
        *.zst) sLoaded=$(zstd -dc "$1" | docker load) ;;
        *.gz)  sLoaded=$(gzip -dc "$1" | docker load) ;;
        *)     sLoaded=$(docker load -i "$1") ;;
    esac || return 1
    sImageRef=$(printf '%s\n' "$sLoaded" \
        | sed -n 's/^Loaded image\( ID\)\{0,1\}: //p' | head -n 1)
    [ -n "$sImageRef" ] || return 1
    : > .vaibify/image_loaded_from_archive
}

# A pull that fails is answered in the order a STRANGER needs. The
# archived copy comes first, because that is the only path open to a
# reproducer without the author's daemon: the registry has forgotten
# the bytes and the deposit still holds them. The copy already on this
# host comes last, because it is survivable for the AUTHOR only -- the
# pinned reference is a digest, so a local copy at that digest IS the
# pinned image, but what the failed pull and the failed load together
# prove is that nobody ELSE can run this script yet. Say which one
# happened rather than silently doing either.
if ! docker pull ${saPlatformOption[@]+"${saPlatformOption[@]}"} "$sImageRef"; then
    if ! fnLoadImageFromArchive; then
        if docker image inspect "$sImageRef" > /dev/null 2>&1; then
            echo "vaibify: could not pull $sImageRef; running the copy" >&2
            echo "  already on this host. A reproducer without that copy" >&2
            echo "  cannot run this script -- archive the image so a" >&2
            echo "  stranger can load it; a registry copy is optional." >&2
        else
            echo "error: cannot pull $sImageRef, no archived copy could" >&2
            echo "  be loaded, and no local copy exists" >&2
            exit 2
        fi
    fi
fi

# --entrypoint bash bypasses the image's development entrypoint. That
# entrypoint configures an interactive workspace: it writes system git
# config (which needs the root phase this invocation does not run, so
# it exits non-zero here), clones the project's configured repos, and
# installs agent tooling. A reproduction wants none of it -- it wants
# the pinned steps, over the mounted repo, and nothing that reaches the
# network or the wall clock.
docker run --rm -i --entrypoint bash \
    ${saPlatformOption[@]+"${saPlatformOption[@]}"} \
    -e "SOURCE_DATE_EPOCH=$sSourceDateEpoch" \
    -v "$PWD":/work -w /work "$sImageRef" \
    -s <<'VAIBIFY_REPRODUCE_EOF'
set -euo pipefail
if [ -n "${SOURCE_DATE_EPOCH:-}" ]; then
    export MPLCONFIGDIR='/tmp/vaibifyMatplotlib' && { mkdir -p '/tmp/vaibifyMatplotlib' && printf '%s\n' "svg.hashsalt: $SOURCE_DATE_EPOCH" > '/tmp/vaibifyMatplotlib/matplotlibrc' || echo 'vaibify: matplotlib svg.hashsalt not pinned' >&2; }
else
    unset SOURCE_DATE_EPOCH
fi
pip install --require-hashes -r requirements.lock
# Step: AiPowerOverTime
( cd 'AiPowerOverTime' && \
    python3 dataAiPowerOverTime.py --data-file ../aiWasteHeatData.json --output aiPowerFits.json && \
    python3 plotAiPowerOverTime.py --power-fits aiPowerFits.json /work/Plot/aiPowerOverTime.png 
)
# Step: YearsToThresholdContour
( cd 'YearsToThresholdContour' && \
    python3 dataYearsToThresholdContour.py --power-fits /work/AiPowerOverTime/aiPowerFits.json --output-grid yearsToThresholdGrid.npz --output-markers contourMarkers.json && \
    python3 plotYearsToThresholdContour.py --years-grid yearsToThresholdGrid.npz --contour-markers contourMarkers.json /work/Plot/yearsToThresholdContour.png 
)
sha256sum -c MANIFEST.sha256
VAIBIFY_REPRODUCE_EOF
