# vaibify-conftest-version: 5
from pathlib import Path
_PROJECT_REPO = Path('/workspace/aigreenhouse')
_MARKER_BASE = _PROJECT_REPO / '.vaibify' / 'test_markers'
_PROJECTS_DIR = _PROJECT_REPO / '.vaibify' / 'projects'
_WORKFLOWS_DIR = _PROJECT_REPO / '.vaibify' / 'workflows'
def _flistProjectJsons():
    listFiles = []
    for _sDir in (_PROJECTS_DIR, _WORKFLOWS_DIR):
        if _sDir.is_dir():
            listFiles.extend(sorted(_sDir.glob('*.json')))
    return listFiles
_T_INTERACTIVE_FALSE_TOKENS = ('', 'false', '0', 'no', 'off', 'none', 'null')
def fbStepIsInteractive(dictStep):
    """Return True iff the step is declared interactive.

    The single classifier for ``bInteractive``. Real booleans pass
    through; a JSON string is read as the word it spells rather than
    as a non-empty object; everything else, ``null`` and absence
    included, is automated.
    """
    if not isinstance(dictStep, dict):
        return False
    valueFlag = dictStep.get("bInteractive", False)
    if isinstance(valueFlag, str):
        return valueFlag.strip().lower() \
            not in _T_INTERACTIVE_FALSE_TOKENS
    return bool(valueFlag)

def flistComputeAllStepLabels(listSteps):
    """Return per-step labels in one linear pass over ``listSteps``.

    Counts automated and interactive steps inline so the whole label
    vector is produced in O(N) time instead of the historical O(N**2)
    cost incurred by per-step ``fsLabelFromStepIndex`` calls.
    """
    listLabels = []
    iAutomated = 0
    iInteractive = 0
    for dictStep in listSteps:
        if fbStepIsInteractive(dictStep):
            iInteractive += 1
            listLabels.append(f"I{iInteractive:02d}")
        else:
            iAutomated += 1
            listLabels.append(f"A{iAutomated:02d}")
    return listLabels


"""Vaibify test result marker plugin.

Auto-generated by vaibify. Do not remove.
Writes a JSON result marker after every pytest session so the
dashboard can detect test outcomes regardless of how pytest was invoked.
Records git blob SHA1 digests of the step's output files so a fresh
clone can reconstruct staleness state.
"""

import hashlib
import json
import os
import time
from datetime import datetime, timezone

_CATEGORY_MAP = {
    "test_integrity": "integrity",
    "test_qualitative": "qualitative",
    "test_quantitative": "quantitative",
}


def _fsGetCategory(sNodeId):
    """Map a test node ID to a category name."""
    for sPrefix, sCategory in _CATEGORY_MAP.items():
        if sPrefix in sNodeId:
            return sCategory
    return "other"


def _fdictBuildCategoryResults(session):
    """Tally pass/fail counts per test category from session items."""
    dictCategories = {}
    for item in session.items:
        sCategory = _fsGetCategory(item.nodeid)
        dictCat = dictCategories.setdefault(
            sCategory, {"iPassed": 0, "iFailed": 0}
        )
        if not hasattr(item, "rep_call") or item.rep_call is None:
            continue
        if item.rep_call.passed:
            dictCat["iPassed"] += 1
        elif item.rep_call.failed:
            dictCat["iFailed"] += 1
    return dictCategories


def _fsStepDirRepoRel(sDir):
    """Return a step directory as a posix path relative to the project repo.

    Accepts container-absolute paths whose prefix matches
    ``_PROJECT_REPO`` (e.g. ``/workspace/ProjectRepo/step1``), legacy
    workspace-rooted paths, or already-relative paths. Produces a
    normalized repo-relative posix string so the workflow's
    repo-relative entries and the live ``__file__``-derived directory
    compare on equal footing.
    """
    if not sDir:
        return ""
    sNorm = os.path.normpath(sDir)
    sRepo = os.path.normpath(str(_PROJECT_REPO))
    if sNorm == sRepo:
        return ""
    if sNorm.startswith(sRepo + os.sep):
        sNorm = sNorm[len(sRepo) + 1:]
    elif sNorm.startswith("/"):
        sNorm = sNorm.lstrip("/")
    return sNorm.replace(os.sep, "/")


def _fsRepoRelFromFile(sFile, sStepDirRel):
    """Return a workflow's file entry as a repo-relative posix path."""
    sFilePosix = sFile.replace(os.sep, "/")
    sRepoPosix = str(_PROJECT_REPO).replace(os.sep, "/")
    if sFilePosix.startswith(sRepoPosix + "/"):
        return sFilePosix[len(sRepoPosix) + 1:]
    if sFilePosix.startswith("/"):
        return sFilePosix.lstrip("/")
    if sStepDirRel:
        sJoined = sStepDirRel + "/" + sFilePosix
    else:
        sJoined = sFilePosix
    return os.path.normpath(sJoined).replace(os.sep, "/")


def _flistStepOutputFiles(sStepDir):
    """Return repo-relative posix paths of the step's output files.

    Reads every workflow JSON under ``.vaibify/workflows`` and
    collects files from the step whose directory (repo-relative)
    matches sStepDir's repo-relative form. Duplicates are removed
    while order is preserved.
    """
    listResult = []
    setSeen = set()
    sWantedRel = _fsStepDirRepoRel(sStepDir)
    for pathJson in _flistProjectJsons():
        try:
            dictWorkflow = json.loads(pathJson.read_text())
        except (OSError, ValueError):
            continue
        for dictStep in dictWorkflow.get("listSteps", []):
            sCandidateRel = _fsStepDirRepoRel(
                dictStep.get("sDirectory", "")
            )
            if sCandidateRel != sWantedRel:
                continue
            for sKey in ("saOutputDataFiles", "saPlotFiles"):
                for sFile in dictStep.get(sKey, []):
                    if "{" in sFile:
                        continue
                    sRel = _fsRepoRelFromFile(sFile, sWantedRel)
                    if sRel and sRel not in setSeen:
                        listResult.append(sRel)
                        setSeen.add(sRel)
    return listResult


def _fsBlobSha(sHostPath):
    """Return the git-blob SHA1 for a file, or empty string on error."""
    try:
        with open(sHostPath, "rb") as handle:
            baContent = handle.read()
    except OSError:
        return ""
    sHeader = "blob " + str(len(baContent)) + chr(0)
    hasher = hashlib.sha1()
    hasher.update(sHeader.encode("utf-8"))
    hasher.update(baContent)
    return hasher.hexdigest()


def _fdictComputeOutputHashes(sStepDir):
    """Return {repo-rel-path: blob-sha} for the step's output files."""
    dictHashes = {}
    for sRel in _flistStepOutputFiles(sStepDir):
        sAbs = str(_PROJECT_REPO / sRel)
        sSha = _fsBlobSha(sAbs)
        if sSha:
            dictHashes[sRel] = sSha
    return dictHashes


def _flistStepInputFiles(sStepDir):
    """Return repo-relative posix paths of the step's input data files.

    Unlike output entries, ``saInputDataFiles`` values are already
    repo-relative — they are never joined onto the step directory.
    """
    listResult = []
    setSeen = set()
    sWantedRel = _fsStepDirRepoRel(sStepDir)
    for pathJson in _flistProjectJsons():
        try:
            dictWorkflow = json.loads(pathJson.read_text())
        except (OSError, ValueError):
            continue
        for dictStep in dictWorkflow.get("listSteps", []):
            sCandidateRel = _fsStepDirRepoRel(
                dictStep.get("sDirectory", "")
            )
            if sCandidateRel != sWantedRel:
                continue
            for sFile in dictStep.get("saInputDataFiles", []):
                if "{" in sFile:
                    continue
                sRel = _fsRepoRelFromFile(sFile, "")
                if sRel and sRel not in setSeen:
                    listResult.append(sRel)
                    setSeen.add(sRel)
    return listResult


def _fdictComputeInputHashes(sStepDir):
    """Return {repo-rel-path: blob-sha} for the step's input data files."""
    dictHashes = {}
    for sRel in _flistStepInputFiles(sStepDir):
        sAbs = str(_PROJECT_REPO / sRel)
        sSha = _fsBlobSha(sAbs)
        if sSha:
            dictHashes[sRel] = sSha
    return dictHashes


def _fsLabelForStep(sStepDirRel):
    """Return a display label (A09, I01) for a step by repo-rel dir.

    Scans workflow JSONs for a step whose directory matches and
    computes the label from its position among same-type steps.
    Returns an empty string when no match exists.
    """
    for pathJson in _flistProjectJsons():
        try:
            dictWorkflow = json.loads(pathJson.read_text())
        except (OSError, ValueError):
            continue
        sLabel = _fsLabelWithinWorkflow(dictWorkflow, sStepDirRel)
        if sLabel:
            return sLabel
    return ""


def _fsLabelWithinWorkflow(dictWorkflow, sStepDirRel):
    """Return sLabel for sStepDirRel within one workflow, or empty.

    Labels come from the transcribed host derivation
    (flistComputeAllStepLabels), never from an inline count, so a
    marker written in the container names the same step the dashboard
    names.
    """
    listSteps = dictWorkflow.get("listSteps", [])
    listLabels = flistComputeAllStepLabels(listSteps)
    for iIndex, dictStep in enumerate(listSteps):
        sCandidate = _fsStepDirRepoRel(dictStep.get("sDirectory", ""))
        if sCandidate == sStepDirRel:
            return listLabels[iIndex]
    return ""


def _fsActiveWorkflowSlug():
    """Return the slug subdir markers go into for this pytest run.

    Reads VAIBIFY_ACTIVE_WORKFLOW_SLUG (set by the pipeline runner).
    Falls back to the first workflow JSON in _WORKFLOWS_DIR for manual
    pytest invocations in single-workflow repos. Returns "default"
    only when both inputs are absent — the conftest must always pick
    some non-empty slug so writes don't escape the namespace.
    """
    sSlug = os.environ.get("VAIBIFY_ACTIVE_WORKFLOW_SLUG", "").strip()
    if sSlug:
        return sSlug
    for pathJson in _flistProjectJsons():
        return pathJson.stem
    return "default"


def pytest_sessionfinish(session, exitstatus):
    """Write a JSON marker after every pytest run."""
    sStepDir = str(Path(__file__).resolve().parent.parent)
    sStepDirRel = _fsStepDirRepoRel(sStepDir)
    fNow = time.time()
    dictMarker = {
        "sDirectory": sStepDirRel,
        "sLabel": _fsLabelForStep(sStepDirRel),
        "iExitStatus": exitstatus,
        "fTimestamp": fNow,
        "sRunAtUtc": datetime.fromtimestamp(
            fNow, tz=timezone.utc,
        ).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "iCollected": session.testscollected,
        "dictCategories": _fdictBuildCategoryResults(session),
        "dictOutputHashes": _fdictComputeOutputHashes(sStepDir),
        "dictInputHashes": _fdictComputeInputHashes(sStepDir),
    }
    sMarkerDir = _MARKER_BASE / _fsActiveWorkflowSlug()
    sMarkerDir.mkdir(parents=True, exist_ok=True)
    sFilename = sStepDirRel.replace("/", "_") + ".json"
    (sMarkerDir / sFilename).write_text(
        json.dumps(dictMarker, indent=2)
    )


import pytest

@pytest.hookimpl(hookwrapper=True)
def pytest_runtest_makereport(item, call):
    """Store the call report on the item for sessionfinish access."""
    outcome = yield
    if call.when == "call":
        item.rep_call = outcome.get_result()
