"""Integrity tests generated by vaibify."""
# vaibify-template-hash: a0b0edd935351486

import json
import os
import pathlib

import numpy as np
import pytest

try:
    import h5py
except ImportError:
    h5py = None

try:
    import csv as csvModule
except ImportError:
    csvModule = None


def _fdictLoadIntegrityStandards():
    """Load the integrity standards JSON file."""
    # The standards file carries the SAME step suffix as this test
    # file ("test_integrity_<step>.py" pairs with
    # "integrity_standards_<step>.json"), derived from __file__ so
    # one template serves suffixed and legacy fixed names alike.
    sSuffix = pathlib.Path(__file__).stem[len("test_integrity"):]
    sJsonPath = str(
        pathlib.Path(__file__).parent
        / ("integrity_standards" + sSuffix + ".json")
    )
    with open(sJsonPath, encoding="utf-8") as fileHandle:
        return json.load(fileHandle)


_DICT_STANDARDS = _fdictLoadIntegrityStandards()
_LIST_STANDARDS = _DICT_STANDARDS["listStandards"]
_STEP_DIRECTORY = str(pathlib.Path(__file__).parent.parent)


def _fnCheckFileExists(sFullPath):
    """Assert the file exists and is non-empty."""
    assert os.path.isfile(sFullPath), f"File not found: {sFullPath}"
    assert os.path.getsize(sFullPath) > 0, f"File is empty: {sFullPath}"


def _fnCheckShape(daData, tExpectedShape, sFullPath):
    """Assert the data array shape matches the expected shape."""
    if tExpectedShape is not None:
        assert list(daData.shape) == tExpectedShape, (
            f"{sFullPath}: expected shape {tExpectedShape}, "
            f"got {list(daData.shape)}"
        )


def _fnCheckNanInf(daData, bCheckNaN, bCheckInf, sFullPath):
    """Assert no NaN or Inf values in numeric data."""
    if not np.issubdtype(daData.dtype, np.number):
        return
    if bCheckNaN:
        assert not np.any(np.isnan(daData)), (
            f"{sFullPath}: contains NaN values"
        )
    if bCheckInf:
        assert not np.any(np.isinf(daData)), (
            f"{sFullPath}: contains Inf values"
        )


def _fnCheckNpy(sFullPath, dictStandard):
    """Validate a numpy .npy file."""
    daData = np.load(sFullPath, allow_pickle=False)
    tShape = dictStandard.get("tExpectedShape")
    _fnCheckShape(daData, tShape, sFullPath)
    _fnCheckNanInf(
        daData, dictStandard.get("bCheckNaN", False),
        dictStandard.get("bCheckInf", False), sFullPath,
    )


def _fnCheckNpz(sFullPath, dictStandard):
    """Validate a numpy .npz archive."""
    archiveNpz = np.load(sFullPath, allow_pickle=False)
    assert len(archiveNpz.files) > 0, f"{sFullPath}: empty npz archive"
    for sKey in archiveNpz.files:
        daData = archiveNpz[sKey]
        if np.issubdtype(daData.dtype, np.number):
            _fnCheckNanInf(
                daData, dictStandard.get("bCheckNaN", False),
                dictStandard.get("bCheckInf", False), sFullPath,
            )


def _fnCheckCsv(sFullPath, dictStandard):
    """Validate a CSV file."""
    import csv
    with open(sFullPath, newline="", encoding="utf-8") as fileHandle:
        listRows = list(csv.DictReader(fileHandle))
    tShape = dictStandard.get("tExpectedShape")
    if tShape is not None and len(tShape) >= 1:
        assert len(listRows) == tShape[0], (
            f"{sFullPath}: expected {tShape[0]} rows, got {len(listRows)}"
        )
    if dictStandard.get("bCheckNaN", False):
        for dictRow in listRows:
            for sVal in dictRow.values():
                try:
                    fVal = float(sVal)
                    assert not np.isnan(fVal), (
                        f"{sFullPath}: contains NaN"
                    )
                    if dictStandard.get("bCheckInf", False):
                        assert not np.isinf(fVal), (
                            f"{sFullPath}: contains Inf"
                        )
                except ValueError:
                    pass


def _fnCheckJson(sFullPath, dictStandard):
    """Validate a JSON file."""
    with open(sFullPath, encoding="utf-8") as fileHandle:
        json.load(fileHandle)


def _fnCheckHdf5(sFullPath, dictStandard):
    """Validate an HDF5 file."""
    assert h5py is not None, "h5py is not installed"
    with h5py.File(sFullPath, "r") as fileHandle:
        assert len(fileHandle.keys()) > 0, f"{sFullPath}: empty HDF5 file"
        if dictStandard.get("bCheckNaN", False):
            def fnCheckDataset(sName, obj):
                if isinstance(obj, h5py.Dataset):
                    daData = np.array(obj)
                    if np.issubdtype(daData.dtype, np.number):
                        _fnCheckNanInf(
                            daData, True,
                            dictStandard.get("bCheckInf", False),
                            sFullPath,
                        )
            fileHandle.visititems(fnCheckDataset)


def _fnCheckWhitespace(sFullPath, dictStandard):
    """Validate a whitespace-delimited file."""
    with open(sFullPath, encoding="utf-8") as fileHandle:
        listRows = [
            s for s in fileHandle if s.strip()
            and not s.strip().startswith("#")
        ]
    tShape = dictStandard.get("tExpectedShape")
    if tShape is not None and len(tShape) >= 1:
        assert len(listRows) >= tShape[0], (
            f"{sFullPath}: expected >= {tShape[0]} rows"
        )
    if dictStandard.get("bCheckNaN", False):
        for sLine in listRows:
            for sToken in sLine.split():
                try:
                    fVal = float(sToken)
                    assert not np.isnan(fVal)
                    if dictStandard.get("bCheckInf", False):
                        assert not np.isinf(fVal)
                except ValueError:
                    pass


def _fnCheckKeyvalue(sFullPath, dictStandard):
    """Validate a key=value text file."""
    with open(sFullPath, encoding="utf-8") as fileHandle:
        listLines = [s for s in fileHandle if "=" in s]
    assert len(listLines) > 0, f"{sFullPath}: no key=value pairs"


def _fnCheckJsonl(sFullPath, dictStandard):
    """Validate a JSON Lines file."""
    import json as jsonMod
    with open(sFullPath, encoding="utf-8") as fileHandle:
        listRecords = [jsonMod.loads(s) for s in fileHandle if s.strip()]
    assert len(listRecords) > 0, f"{sFullPath}: empty JSONL"


def _fnCheckGenericText(sFullPath, dictStandard):
    """Validate a generic text file by checking it is non-empty."""
    with open(sFullPath, encoding="utf-8") as fileHandle:
        sContent = fileHandle.read()
    assert len(sContent.strip()) > 0, f"{sFullPath}: empty file"


_DICT_INTEGRITY_CHECKERS = {
    "npy": _fnCheckNpy,
    "npz": _fnCheckNpz,
    "csv": _fnCheckCsv,
    "json": _fnCheckJson,
    "hdf5": _fnCheckHdf5,
    "whitespace": _fnCheckWhitespace,
    "keyvalue": _fnCheckKeyvalue,
    "jsonl": _fnCheckJsonl,
}


def _fnDispatchIntegrityCheck(sFullPath, dictStandard):
    """Load and check the file using the appropriate format checker."""
    sFormat = dictStandard.get("sFormat", "")
    fnChecker = _DICT_INTEGRITY_CHECKERS.get(
        sFormat, _fnCheckGenericText,
    )
    fnChecker(sFullPath, dictStandard)


if not _LIST_STANDARDS:
    def test_no_integrity_outputs():
        """Placeholder when no data files are present."""
        assert True
else:
    @pytest.mark.parametrize(
        "dictStandard",
        _LIST_STANDARDS,
        ids=[s["sFileName"] for s in _LIST_STANDARDS],
    )
    def test_integrity_check(dictStandard):
        """Validate structural integrity of a data file."""
        sFullPath = os.path.join(
            _STEP_DIRECTORY, dictStandard["sFileName"],
        )
        _fnCheckFileExists(sFullPath)
        _fnDispatchIntegrityCheck(sFullPath, dictStandard)
